POST http://localhost:8000/api/payments
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "id": 1,
  "value": "1 PLN"
}

###

GET http://localhost:8000/api/payments/27053bac-8008-4171-a503-12fd0ce19226
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###

GET http://localhost:8000/api/payments/started?pageSize=3&pageNumber=1
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###

GET http://localhost:8000/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==
