POST http://localhost:8000/api/payments
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "id": 1,
  "value": "1 PLN"
}

###

GET http://localhost:8000/api/payments/27053bac-8008-4171-a503-12fd0ce19226
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8000/api/payments/started?pageSize=3&pageNumber=1
Accept: application/json
Content-Type: application/json
Authorization: bearer {{token}}

###

GET http://localhost:8000/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###

//@no-cookie-jar
//@no-redirect
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=password&username=jan&password=123

> {%
   client.global.set('token', response.body.access_token);
%}

###

//@no-cookie-jar
//@no-redirect
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxN2Q1Nzg3ZS03YWQ3LTRiMTMtOGU2Mi0wZTZjODlmM2Y0YmEifQ.eyJleHAiOjE3MTI4Mzg2ODksImlhdCI6MTcxMjgzNjg4OSwianRpIjoiZWMzYzM2N2ItZDljNi00ZGE3LTlkOWYtNDcxMTEyYjZhNjFiIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTAwL3JlYWxtcy90cmFpbmluZyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODEwMC9yZWFsbXMvdHJhaW5pbmciLCJzdWIiOiJhNThjNzliMS1iMDc1LTRmM2UtOGE0My00MDgyMjU1ZWIzMGEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoidHJhaW5pbmctY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjEzZTVkNjg5LTg1ODYtNGI3NC04YWQyLTMzOTk4NjVhOTI5MiIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjEzZTVkNjg5LTg1ODYtNGI3NC04YWQyLTMzOTk4NjVhOTI5MiJ9.GRkvSz6KOSY_mhJhRHXcdiMq-dY0Vy1c732voErSIYDBj8SSqQX_xmy62h0uloOzeNfXLaXGlpegOryn_fRPMg
