//@no-redirect
//@no-cookie-jar
POST http://localhost:8080/api/payments
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

//@no-redirect
//@no-cookie-jar
GET http://localhost:8080/api/payments/1
Accept: application/json
Content-Type: application/json

###

//@no-redirect
//@no-cookie-jar
GET http://localhost:8080/api/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=shop-client&grant_type=password&username=jan&password=123

> {%
client.global.set("token", response.body.access_token);
client.global.set("refreshToken", response.body.refresh_token);
%}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=shop-client&grant_type=refresh_token&refresh_token={{refreshToken}}

> {%
client.global.set("token", response.body.access_token);
client.global.set("refreshToken", response.body.refresh_token);
%}
