GET http://localhost:8080/api/payments?pageSize=2&status=STARTED
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDAwIiwidXNlciI6ImphbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNzY2MDY1ODI4fQ.A5rEzTTmVFSouyG2qE_QzYKV9cOdVfPyluyhnewN2rY
#Authorization: API_KEY 1234567890
Authorization: bearer {{token}}

###

POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "value": "100 PLN"
}

###

GET  http://localhost:8080/api/payments/bda105dd-9bc4-4975-b328-fa0e5c16d849
Accept: application/json
Content-Type: application/json

###

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=password&username=jan&password=123

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=refresh_token&refresh_token={{ refreshToken }}

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

