GET http://localhost:8080/api/payments?pageSize=2&status=STARTED
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDAwIiwidXNlciI6ImphbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNzY2MDY1ODI4fQ.A5rEzTTmVFSouyG2qE_QzYKV9cOdVfPyluyhnewN2rY
Authorization: API_KEY 1234567890

###

POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "value": "100 PLN"
}

###

GET  http://localhost:8080/api/payments/bda105dd-9bc4-4975-b328-fa0e5c16d849
Accept: application/json
Content-Type: application/json
