version: '3.9'
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
