server:
  port: 8000
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    open-in-view: false
  #  jpa:
#    hibernate:
#      ddl-auto: create-drop
  data:
    mongodb:
      username: admin
      password: admin
      database: payments
      host: localhost
      port: 27017
      authentication-database: admin
      # auto-index-creation: true
logging:
  level:
    org.javamoney.moneta: OFF

