spring:
  datasource:
    url: jdbc:h2:file:./data/h2-db.db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
server:
  servlet:
    session:
      timeout: 3600s
      cookie:
        max-age: 3600s
