server:
  port: 8000
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    open-in-view: false # true skutkuje otworzeniem dodatkowej transakcji na poziomie widoku (zaszlość historyczna/ant pattern), należy ustawić na fals
#  jpa:
#    hibernate:
#      ddl-auto: create
  data:
    mongodb:
      username: admin
      password: admin
      database: payments
      host: localhost
      port: 27017
      authentication-database: admin
      # auto-index-creation: true
  messages:
    basename: exceptions,text
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
      client:
        registration:
#          github:
#            client-id: Ov23liAgsFga5nl04OFc
#            client-secret: 5cb532864d1f6db4a8ffd9b0d1f2ce89b5963983
          keycloak:
            client-id: training-client
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/training
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
logging:
  level:
    org.javamoney.moneta: OFF