spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  messages:
    basename: messages,exceptions
#  security:
#    user:
#      name: jan
#      password: 123
#      roles: ADMIN
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: secretsecret