server:
  port: 8000
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    open-in-view: false # true skutkuje otworzeniem dodatkowej transakcji na poziomie widoku (zaszlość historyczna/ant pattern), należy ustawić na fals
  #  jpa:
#    hibernate:
#      ddl-auto: create-drop
  data:
    mongodb:
      username: admin
      password: admin
      database: payments
      host: localhost
      port: 27017
      authentication-database: admin
      # auto-index-creation: true
  messages:
    basename: exceptions,text
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/training
        registration:
          keycloak:
            client-id: training-client
            scope:
              - openid
#          github:
#            client-id: Ov23li3jAyd5a1PylMo4
#            client-secret: ea9a685e3ecc9c664e283165eb2c95a9d7a68c1b



#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
logging:
  level:
    org.javamoney.moneta: OFF