server:
  port: 8000
spring:
  mail:
    host: localhost
    port: 10025
  #    host: smtp.gmail.com
  #    port: 587
  #    username: username
  #    password: password
  #    properties:
  #      mail.smtp.auth: true
  #      mail.smtp.starttls.enable: true
  #      mail.smtp.ssl.trust: smtp.gmail.com
  artemis:
    broker-url: tcp://localhost:61616 # default
    embedded:
      enabled: true
  jms:
    listener:
      max-concurrency: 10
      min-concurrency: 1
    pub-sub-domain: false #queue

